# Generated by Django 6.0.6 on 2026-06-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='changes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
