# Generated by Django 6.0.6 on 2026-06-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_registrationorder_registration_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
