# Generated by Django 6.0.6 on 2026-06-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_registration_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationorder',
            name='payment_method',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('free', 'Free Registration'), ('admin', 'Manual Admin Entry')], default='free', max_length=20),
        ),
    ]
