# Generated by Django 6.0.6 on 2026-06-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_registrationorder_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='name',
        ),
        migrations.AddField(
            model_name='registration',
            name='first_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='last_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
