# Generated by Django 6.0.6 on 2026-06-11 09:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_remove_registration_name_registration_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationorder',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
