# Generated by Django 6.0.6 on 2026-06-11 09:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_registrationorder_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationorder',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
