# Generated by Django 6.0.6 on 2026-06-08 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('registrations', '0002_registrationorder_registration_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='registration',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='registrations.registrationorder'),
        ),
    ]
