# Generated by Django 6.0.6 on 2026-06-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ticket_type', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quantity_type', models.CharField(choices=[('limited', 'Limited'), ('unlimited', 'Unlimited')], max_length=20)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('duplicate_email_check', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
