# Generated by Django 6.0.6 on 2026-06-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='max_per_order',
            field=models.PositiveIntegerField(default=10, help_text='Maximum tickets allowed per single purchase.'),
        ),
    ]
