# Generated by Django 6.0.6 on 2026-06-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_max_per_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='max_per_order',
            field=models.PositiveIntegerField(default=50, help_text='Maximum tickets allowed per single purchase.'),
        ),
    ]
